version: '3.4'

services:

    router:
        image: binocarlos/noxy
        ports:
            - 80:80
        container_name: router
        environment:
            - NOXY_DEFAULT_HOST=ui
            - NOXY_DEFAULT_PORT=3031
            - NOXY_DEFAULT_WS=1
            - NOXY_API_FRONT=/api
            - NOXY_API_HOST=server
            - NOXY_API_PORT=9000
        networks:
            - paulwizviz_react_desktop_network

    ui:
        build:
            context: ../
            dockerfile: ./build/ui.dev.dockerfile
        image: ${UI_IMAGE}
        container_name: ui
        expose:
            - 3031
        ports:
            - 3031:3031
        volumes:
            - ../ui/webpack:/opt/webpack
            - ../ui/images:/opt/images
            - ../ui/src:/opt/src
            - ../ui/.eslintrc.json:/opt/.eslintrc.json
            - ../ui/.babelrc:/opt/.babelrc
        networks:
            - paulwizviz_react_desktop_network

    server:
        build:
            context: ../
            dockerfile: ./build/server.dockerfile
        image: ${SERVER_IMAGE}
        container_name: server
        expose:
            - 9000
        ports:
            - 9000:9000
        volumes: 
            - ../server/src:/opt/src
        networks:
            - paulwizviz_react_desktop_network

networks:
    paulwizviz_react_desktop_network:
